Bab 342 implement verify incoming transaction into ninja
p2ppsr/utxoninja pull request #11
Opened 2022-08-16 19:04 UTC by BraydenLangley

Tested `verifyIncomingTransaction` with the tempo-key-server pay route.
Tested updated `processPendingTransaction` by calling the route when two unprocessed transactions were created.

2022-08-16 19:28 UTC, ty-everett requested changes
The logic for extracting pending transactions is good. We'll want to add some more validation, ane ensure that multi-output transactions are supported. I can help answer questions about my comments and suggested changes.

2022-08-16 19:28 UTC, ty-everett commented on src/index.js
> +      const [outputs] = transaction.outputs
```suggestion
      const [firstOutput] = transaction.outputs
```
This destructures the array, and checks the first output only. We should check every output, because the Paymail BRFC spec says that multiple oututs could be provided.

Is the amount of the transaction returned? If so, we should check the amount of the transaction, rather than to check the first output only.

Allowing multiple outputs lets people split things up for privacy, since no one knows if it's all going to the same person, change, fees of some kind, etc. For example, the `paymail` package (when it sent the payment), could have divided the amount in half, and split the payment up across two outputs (each with a separate `derivationSuffix`, but on the same `derivationPrefix`).

2022-08-16 19:28 UTC, ty-everett commented on src/index.js
> +    // Note: This would verify a already processed transaction as well. Is that want we want?
```suggestion
```
Yes, because maybe `processPendingTransactions()` was already called, and batch-processed it along with others. This just checks that it's been validated, one way or the other.

2022-08-16 19:28 UTC, ty-everett commented on src/index.js
> +    if (finalResult.status === 'completed') {
Here, we need to check the other fields on the transaction as well (against what was passed into this function), such as `description`, `amount`, `senderPaymail`, `senderIdentityKey`. This merely checks that some transaction with this reference number was successful, but without checking that the person actually is who we expect, or paid the expected amount, with the expected description.

An attacker cound:
* /invoice
* (Potentially anonymously) send Paymail payment of 1 satoshi
* Wait for the recipient to call `processPendingTransactions` to batch-process all their new payments
* Then, submit the reference number to `/pay`, and it would come up as `status`: `completed` (but only 1 satoshi)
* pwn & 0wn

2022-08-16 22:08 UTC, BraydenLangley commented on src/index.js
> +    if (finalResult.status === 'completed') {
This feels like needs its own helper function since the purpose of this function is to verify an incoming function, not one that has already been processed, right? Also, getTransactions doesn't return the `senderIdentityKey` or `description`. Is there a route that I could possibly use to get the identityKey from a paymail?

2022-08-16 22:13 UTC, ty-everett commented on src/index.js
> +    if (finalResult.status === 'completed') {
Description is returned as `note` in this function. Since it's not readily available, just verify the Paymail, and add a TODO comment for verifying the identityKey.

2022-08-16 22:15 UTC, ty-everett commented on src/index.js
> +    if (finalResult.status === 'completed') {
In terms of moving it to a helper function, I don't think it's necessary — just a matter of extending this if statement with a couple more conditions. The function verifies a transaction that is incoming (`isOutgoing` = `false`), regardless of whether such incoming transaction has been processed or not.

2022-08-17 00:23 UTC, BraydenLangley commented on src/index.js
> +      const [outputs] = transaction.outputs
See [latest commit](https://github.com/p2ppsr/utxoninja/pull/11/commits/b142ae33c3c364e677f4acb75b136b95d64e5cf9) which validates the senderIdentityKey for every output.

2022-08-17 00:36 UTC, ty-everett commented on src/index.js
> +      })
```suggestion
      return new Promise((resolve, reject) => {
        try {
          _processIncomingTransaction({
            authriteClient: this.authriteClient,
            config: this.config,
            incomingTransaction: transaction,
            onTransactionProcessed: () => {
              resolve(true)
            },
            onTransactionFailed: () => {
              resolve(false)
            }
          })
        } catch (e) {
          reject(e)
        }
      })
```

2022-08-17 00:37 UTC, merged